[build]
  command = "npm run build:web"
  publish = "dist"

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
  force = true

[[redirects]]
  from = "/support"
  to = "/support.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
