import { Platform, Vibration } from 'react-native';
import * as Haptics from 'expo-haptics';
import { Audio } from 'expo-av';

export type SoundId =
  | 'answer_correct' | 'answer_wrong' | 'answer_timeout'
  | 'streak_3' | 'streak_5'
  | 'timer_tick' | 'timer_warning'
  | 'battle_start' | 'battle_star_1' | 'battle_star_2' | 'battle_star_3'
  | 'battle_win' | 'battle_lose' | 'battle_draw'
  | 'ui_tap' | 'ui_swipe' | 'ui_category_select'
  | 'game_start' | 'game_end_win' | 'game_end_neutral'
  | 'xp_gain' | 'level_up' | 'daily_challenge_unlock';

// WAV assets generated by generate-sounds.js.
// Replace individual entries with higher-quality files when available.
const AUDIO_SOURCES: Partial<Record<SoundId, number>> = {
  answer_correct:          require('../../assets/sounds/answer_correct.wav'),
  answer_wrong:            require('../../assets/sounds/answer_wrong.wav'),
  answer_timeout:          require('../../assets/sounds/answer_timeout.wav'),
  streak_3:                require('../../assets/sounds/streak_3.wav'),
  streak_5:                require('../../assets/sounds/streak_5.wav'),
  timer_tick:              require('../../assets/sounds/timer_tick.wav'),
  timer_warning:           require('../../assets/sounds/timer_warning.wav'),
  battle_start:            require('../../assets/sounds/battle_start.wav'),
  battle_star_1:           require('../../assets/sounds/battle_star_1.wav'),
  battle_star_2:           require('../../assets/sounds/battle_star_2.wav'),
  battle_star_3:           require('../../assets/sounds/battle_star_3.wav'),
  battle_win:              require('../../assets/sounds/battle_win.wav'),
  battle_lose:             require('../../assets/sounds/battle_lose.wav'),
  battle_draw:             require('../../assets/sounds/battle_draw.wav'),
  ui_tap:                  require('../../assets/sounds/ui_tap.wav'),
  ui_swipe:                require('../../assets/sounds/ui_swipe.wav'),
  ui_category_select:      require('../../assets/sounds/ui_category_select.wav'),
  game_start:              require('../../assets/sounds/game_start.wav'),
  game_end_win:            require('../../assets/sounds/game_end_win.wav'),
  game_end_neutral:        require('../../assets/sounds/game_end_neutral.wav'),
  xp_gain:                 require('../../assets/sounds/xp_gain.wav'),
  level_up:                require('../../assets/sounds/level_up.wav'),
  daily_challenge_unlock:  require('../../assets/sounds/daily_challenge_unlock.wav'),
};

// Android vibration patterns: [delay_ms, on_ms, off_ms, on_ms, ...]
const ANDROID_PATTERNS: Partial<Record<SoundId, number[]>> = {
  answer_correct: [0, 50],
  answer_wrong: [0, 80, 60, 80],
  answer_timeout: [0, 120],
  streak_3: [0, 40, 30, 40, 30, 80],
  streak_5: [0, 40, 20, 40, 20, 40, 20, 120],
  timer_warning: [0, 30],
  battle_star_1: [0, 60],
  battle_star_2: [0, 60, 40, 60],
  battle_star_3: [0, 60, 30, 60, 30, 120],
  battle_win: [0, 80, 40, 80, 40, 200],
  battle_lose: [0, 150],
  game_start: [0, 60, 40, 60, 40, 60],
  level_up: [0, 60, 30, 60, 30, 60, 30, 200],
};

const soundCache: Partial<Record<SoundId, Audio.Sound>> = {};

let soundEnabled = true;
let hapticsEnabled = true;
let muteTimerTicks = false;

export function setSoundEnabled(val: boolean) { soundEnabled = val; }
export function setHapticsEnabled(val: boolean) { hapticsEnabled = val; }
export function setMuteTimerTicks(val: boolean) { muteTimerTicks = val; }

export async function preloadSounds() {
  const sources = Object.entries(AUDIO_SOURCES) as [SoundId, number][];
  if (sources.length === 0) return;
  try {
    await Audio.setAudioModeAsync({ playsInSilentModeIOS: false, staysActiveInBackground: false });
    for (const [id, source] of sources) {
      try {
        const { sound } = await Audio.Sound.createAsync(source, { shouldPlay: false });
        soundCache[id] = sound;
      } catch {}
    }
  } catch {}
}

function hapticFeedback(eventId: SoundId) {
  if (!hapticsEnabled || Platform.OS === 'web') return;

  if (Platform.OS === 'android') {
    const pattern = ANDROID_PATTERNS[eventId];
    if (pattern) Vibration.vibrate(pattern);
    return;
  }

  // iOS — map event IDs to expo-haptics impulses
  switch (eventId) {
    case 'answer_correct':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      break;
    case 'answer_wrong':
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);
      break;
    case 'answer_timeout':
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning);
      break;
    case 'streak_3':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy), 70);
      break;
    case 'streak_5':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 60);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy), 120);
      break;
    case 'timer_warning':
      Haptics.selectionAsync();
      break;
    case 'battle_star_1':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      break;
    case 'battle_star_2':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 100);
      break;
    case 'battle_star_3':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 90);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy), 180);
      break;
    case 'battle_win':
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      break;
    case 'battle_lose':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Heavy);
      break;
    case 'battle_draw':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      break;
    case 'game_start':
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light), 100);
      setTimeout(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium), 200);
      break;
    case 'level_up':
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      break;
    case 'ui_tap':
    case 'ui_swipe':
    case 'ui_category_select':
      Haptics.selectionAsync();
      break;
    default:
      break;
  }
}

export function play(eventId: SoundId) {
  const isTimerEvent = eventId === 'timer_tick' || eventId === 'timer_warning';
  if (isTimerEvent && muteTimerTicks) return;

  if (soundEnabled) {
    const sound = soundCache[eventId];
    if (sound) {
      sound.stopAsync().then(() => sound.playAsync()).catch(() => {});
    }
  }

  hapticFeedback(eventId);
}
