INSERT INTO remote_questions (id, category_id, question, answers, correct_index, difficulty, active)
VALUES
  ('fd_001', 'food', 'Vad kallas den femte grundsmaken, utöver sött, surt, salt och bittert?', ARRAY['Kryddigt', 'Umami', 'Fett', 'Stärkelse'], 1, 'easy', true),
  ('fd_002', 'food', 'Vilket land är sushi ursprungligen från?', ARRAY['Kina', 'Korea', 'Japan', 'Thailand'], 2, 'easy', true),
  ('fd_003', 'food', 'Vad är huvudingrediensen i guacamole?', ARRAY['Tomat', 'Lime', 'Koriander', 'Avokado'], 3, 'easy', true),
  ('fd_004', 'food', 'Vilken innertemperatur har en biff vid "medium rare"?', ARRAY['45–50°C', '55–57°C', '62–65°C', '70–75°C'], 1, 'medium', true),
  ('fd_006', 'food', 'Vad är "mirepoix"?', ARRAY['En fransk sås', 'Lök, morot och selleri', 'En typ av pasta', 'En vinregion i Frankrike'], 1, 'medium', true),
  ('fd_009', 'food', 'Vad kallas tekniken att tillaga mat i vakuumförpackning i vattenbad vid låg temperatur?', ARRAY['Confit', 'Sous vide', 'Bain-marie', 'Blanquette'], 1, 'hard', true),
  ('fd_013', 'food', 'Vad är "Maillard-reaktionen"?', ARRAY['En jäsningsprocess i öl', 'En kemisk reaktion mellan protein och socker vid upphettning som ger brynt yta och smak', 'En teknik för att emulgera såser', 'En metod för att konservera kött'], 1, 'hard', true),
  ('fd_018', 'food', 'Vad kallas ytan som bränns på en crème brûlée?', ARRAY['Karamelliserat socker', 'Glaserad grädde', 'Brûlé-skikt', 'Pralin'], 0, 'medium', true),
  ('fd_024', 'food', 'Vad mäter Scoville-skalan?', ARRAY['Syrahalt i vin', 'Hettan i chilipeppar', 'Bitterhet i kaffe', 'Sockerhalt i druvor'], 1, 'medium', true),
  ('fd_025', 'food', 'Vilket land producerar mest olivolja i världen?', ARRAY['Italien', 'Grekland', 'Spanien', 'Tunisien'], 2, 'hard', true),
  ('fd_026', 'food', 'Vilket naturligt ämne i parmesan och ansjovis ger umami-smak?', ARRAY['Tannin', 'Glutamat', 'Kaprin', 'Lysin'], 1, 'hard', true),
  ('fd_032', 'food', 'Vad kallas processen när en vätska koka ner för att koncentrera smak och tjockna konsistens?', ARRAY['Emulgering', 'Klarning', 'Reduktion', 'Sterilisering'], 2, 'medium', true),
  ('fd_005', 'drink', 'Vilken cocktail innehåller rom, lime och färsk mynta?', ARRAY['Caipirinha', 'Daiquiri', 'Mojito', 'Cuba Libre'], 2, 'easy', true),
  ('fd_007', 'drink', 'Vilka tre druvor används traditionellt i Champagne?', ARRAY['Chardonnay, Riesling och Pinot Gris', 'Chardonnay, Pinot Noir och Pinot Meunier', 'Pinot Noir, Merlot och Cabernet', 'Riesling, Gewürztraminer och Pinot Blanc'], 1, 'medium', true),
  ('fd_008', 'drink', 'Vilken tequila-variant är lagrad i minst 3 år på fat?', ARRAY['Reposado', 'Añejo', 'Extra Añejo', 'Blanco'], 2, 'hard', true),
  ('fd_010', 'drink', 'Vilken cocktail innehåller Kahlúa, vodka och grädde?', ARRAY['Black Russian', 'White Russian', 'Espresso Martini', 'Irish Coffee'], 1, 'medium', true),
  ('fd_011', 'drink', 'Vilket vin serveras traditionellt kylt?', ARRAY['Fylligt rödvin', 'Vitt vin', 'Kraftigt rödvin', 'Portvin'], 1, 'easy', true),
  ('fd_012', 'drink', 'Vad är espresso?', ARRAY['Utspätt kaffe', 'Kokt kaffe med mjölk', 'Starkt kaffe pressat genom malda kaffebönor', 'Iskaffe med sirap'], 2, 'easy', true),
  ('fd_014', 'drink', 'Vad kallas svampen som angriper druvor och koncentrerar sockret för att skapa ädelrötade sötvin?', ARRAY['Candida albicans', 'Aspergillus niger', 'Botrytis cinerea', 'Penicillium roqueforti'], 2, 'hard', true),
  ('fd_015', 'drink', 'Vilka tre ingredienser innehåller en klassisk Negroni?', ARRAY['Gin, Campari och torr vermut', 'Gin, Campari och röd vermut', 'Vodka, Campari och röd vermut', 'Gin, Aperol och röd vermut'], 1, 'medium', true),
  ('fd_016', 'drink', 'Vad skapar bubblorna i Champagne?', ARRAY['Koldioxid tillsätts mekaniskt', 'En andra jäsning på flaskan som skapar koldioxid', 'Druvornas naturliga kolsyra', 'En speciell jäst som lever i vinet'], 1, 'medium', true),
  ('fd_017', 'drink', 'Från vilken italiensk region kommer Barolo-vinet?', ARRAY['Toscana', 'Sicilien', 'Piemonte', 'Veneto'], 2, 'hard', true),
  ('fd_019', 'drink', 'Av vilken druva görs vinerna Barolo och Barbaresco?', ARRAY['Sangiovese', 'Nebbiolo', 'Barbera', 'Dolcetto'], 1, 'hard', true),
  ('fd_020', 'drink', 'Vad betyder "terroir" i vinsammanhang?', ARRAY['Vinets årgång', 'Jord, klimat och geografisk plats som formar vinets karaktär', 'Metoden att tappa vin på flaska', 'Vinregionstraditioner för servering'], 1, 'medium', true),
  ('fd_021', 'drink', 'Vad är "amaro"?', ARRAY['Italienskt rödvin', 'Bitter italiensk likör gjord på örter och kryddor', 'En typ av olivolja', 'Torrt mousserande vin'], 1, 'medium', true),
  ('fd_022', 'drink', 'Vad skiljer single malt whisky från blended whisky?', ARRAY['Single malt är dyrare och äldre', 'Single malt kommer från ett enda destilleri; blended är en blandning från flera', 'Single malt är alltid skotsk', 'Blended är alltid av högre kvalitet'], 1, 'medium', true),
  ('fd_023', 'drink', 'Vad är "cold brew"-kaffe?', ARRAY['Iskaffe med grädde', 'Kaffe bryggat med is i kaffemaskinen', 'Kaffe extraherat i kallt vatten under 12–24 timmar', 'Frystorkat kaffe löst i kallt vatten'], 2, 'medium', true),
  ('fd_027', 'drink', 'Vad är skillnaden mellan brandy och cognac?', ARRAY['Det finns ingen skillnad', 'Cognac är en brandy tillverkad i Cognac-regionen i Frankrike enligt strikta regler', 'Brandy görs av vindruvor, cognac av äpplen', 'Cognac är starkare än brandy'], 1, 'hard', true),
  ('fd_028', 'drink', 'Vad är kefir?', ARRAY['En turkisk dessert', 'En fermenterad mjölkdryck rik på probiotiska kulturer', 'En typ av hårdost', 'En Mellanösternkrydda'], 1, 'medium', true),
  ('fd_029', 'drink', 'Vad är sake?', ARRAY['Japanskt risvin tillverkat genom fermentering av ris', 'En japansk whisky', 'Destillerat risbrännvin', 'Koreansk jordgubbslikör'], 0, 'easy', true),
  ('fd_030', 'drink', 'Vilken temperatur rekommenderas för att servera fylligt rödvin?', ARRAY['10–12°C', '13–15°C', '16–18°C', '20–22°C'], 2, 'medium', true),
  ('fd_031', 'drink', 'Vad är calvados?', ARRAY['Spansk druvspiritusa', 'Äppelbrännvin från Normandie i Frankrike', 'Belgisk öllikör', 'Italiensk päronsprit'], 1, 'medium', true),
  ('kp_001', 'famous_profiles', 'Vem är känd för TV-programmet Hell''s Kitchen?', ARRAY['Jamie Oliver', 'Gordon Ramsay', 'Nigella Lawson', 'Heston Blumenthal'], 1, 'easy', true),
  ('kp_002', 'famous_profiles', 'Vilken svensk kock låg bakom restaurangen Fäviken?', ARRAY['Björn Frantzén', 'Magnus Nilsson', 'Tommy Myllymäki', 'Erik Lallerstedt'], 1, 'hard', true),
  ('kp_003', 'famous_profiles', 'Vem grundade restaurangen Noma i Köpenhamn?', ARRAY['Ferran Adrià', 'René Redzepi', 'Alain Ducasse', 'Massimo Bottura'], 1, 'medium', true),
  ('kp_004', 'famous_profiles', 'Vem ledde programmet The Naked Chef?', ARRAY['Jamie Oliver', 'Gordon Ramsay', 'Marco Pierre White', 'Wolfgang Puck'], 0, 'easy', true),
  ('kp_005', 'famous_profiles', 'Vem låg bakom El Bulli?', ARRAY['Heston Blumenthal', 'Ferran Adrià', 'René Redzepi', 'Paul Bocuse'], 1, 'medium', true),
  ('kp_006', 'famous_profiles', 'Vilken svensk kock driver restaurangen Frantzén?', ARRAY['Markus Aujalay', 'Björn Frantzén', 'Niklas Ekstedt', 'Tommy Myllymäki'], 1, 'medium', true),
  ('kp_007', 'famous_profiles', 'Vem är känd för The Fat Duck och molekylär gastronomi?', ARRAY['Gordon Ramsay', 'Heston Blumenthal', 'Alain Ducasse', 'Nobu Matsuhisa'], 1, 'medium', true),
  ('kp_008', 'famous_profiles', 'Vem driver Osteria Francescana?', ARRAY['Massimo Bottura', 'Carlo Cracco', 'Jamie Oliver', 'Gennaro Contaldo'], 0, 'hard', true),
  ('kp_009', 'famous_profiles', 'Vem var Anthony Bourdain?', ARRAY['Sommelier', 'Kock och TV-profil', 'Kritiker', 'Politiker'], 1, 'easy', true),
  ('kp_010', 'famous_profiles', 'Vem anses vara en pionjär inom nouvelle cuisine?', ARRAY['Paul Bocuse', 'René Redzepi', 'Gordon Ramsay', 'Alain Ducasse'], 0, 'hard', true),
  ('kp_011', 'famous_profiles', 'Vem ligger bakom Nobu-restaurangerna?', ARRAY['Nobu Matsuhisa', 'David Chang', 'Ken Hom', 'Roy Choi'], 0, 'medium', true),
  ('kp_012', 'famous_profiles', 'Vilken svensk profil är starkt förknippad med Sveriges mästerkock?', ARRAY['Markus Aujalay', 'Ernst Kirchsteiger', 'Leif Mannerström', 'Per Morberg'], 0, 'easy', true),
  ('kp_013', 'famous_profiles', 'Vem driver Momofuku-restaurangerna?', ARRAY['Wolfgang Puck', 'David Chang', 'Roy Choi', 'Daniel Humm'], 1, 'medium', true),
  ('kp_014', 'famous_profiles', 'Vem blev världskänd genom att lära amerikaner fransk matlagning på TV?', ARRAY['Nigella Lawson', 'Julia Child', 'Martha Stewart', 'Jamie Oliver'], 1, 'medium', true),
  ('kp_015', 'famous_profiles', 'Vem var Storbritanniens yngsta trestjärniga Michelin-kock?', ARRAY['Gordon Ramsay', 'Marco Pierre White', 'Heston Blumenthal', 'Jamie Oliver'], 1, 'hard', true),
  ('kp_016', 'famous_profiles', 'Vilken svensk TV-kock är känd för sitt arbete med hållbar mat och Malmöprofil?', ARRAY['Tareq Taylor', 'Markus Aujalay', 'Niklas Ekstedt', 'Melker Andersson'], 0, 'medium', true),
  ('kp_017', 'famous_profiles', 'Vem driver Eleven Madison Park?', ARRAY['Daniel Humm', 'Eric Ripert', 'Thomas Keller', 'Grant Achatz'], 0, 'hard', true),
  ('kp_018', 'famous_profiles', 'Vem ligger bakom restaurangen Alinea?', ARRAY['Thomas Keller', 'Grant Achatz', 'David Chang', 'Alain Ducasse'], 1, 'hard', true),
  ('kp_019', 'famous_profiles', 'Vem är känd för restaurangen Le Bernardin?', ARRAY['Eric Ripert', 'Daniel Boulud', 'Alain Ducasse', 'Joël Robuchon'], 0, 'hard', true),
  ('kp_020', 'famous_profiles', 'Vem var Joël Robuchon?', ARRAY['Kritiker', 'En av världens mest Michelin-belönade kockar', 'TV-producent', 'Sommelier'], 1, 'medium', true),
  ('kp_021', 'famous_profiles', 'Vem är känd för restaurangen The French Laundry?', ARRAY['Thomas Keller', 'Daniel Humm', 'Massimo Bottura', 'Gordon Ramsay'], 0, 'hard', true),
  ('kp_022', 'famous_profiles', 'Vilken svensk kock är känd från både Bocuse d''Or och TV?', ARRAY['Tommy Myllymäki', 'Erik Lallerstedt', 'Markus Aujalay', 'Leif Mannerström'], 0, 'medium', true),
  ('kp_023', 'famous_profiles', 'Vem populariserade koreansk street food i Los Angeles?', ARRAY['Roy Choi', 'David Chang', 'Nobu Matsuhisa', 'Wolfgang Puck'], 0, 'hard', true),
  ('kp_024', 'famous_profiles', 'Vem byggde ett globalt fine dining-imperium?', ARRAY['Alain Ducasse', 'Jamie Oliver', 'Gordon Ramsay', 'Nigella Lawson'], 0, 'hard', true),
  ('kp_025', 'famous_profiles', 'Vem är känd svensk krögare och domare i Sveriges mästerkock?', ARRAY['Markus Aujalay', 'Tareq Taylor', 'Niklas Ekstedt', 'Leif GW Persson'], 0, 'easy', true),
  ('kp_026', 'famous_profiles', 'Vem är känd för programmet Vad blir det för mat?', ARRAY['Per Morberg', 'Ernst Kirchsteiger', 'Tareq Taylor', 'Edward Blom'], 0, 'easy', true),
  ('kp_027', 'famous_profiles', 'Vem är svensk kock och krögare bakom Ekstedt?', ARRAY['Niklas Ekstedt', 'Björn Frantzén', 'Tommy Myllymäki', 'Markus Aujalay'], 0, 'medium', true),
  ('kp_028', 'famous_profiles', 'Vem är känd för sitt stora intresse för mat, dryck och kulturhistoria?', ARRAY['Edward Blom', 'Leif Mannerström', 'Ernst Kirchsteiger', 'Paolo Roberto'], 0, 'medium', true),
  ('kp_029', 'famous_profiles', 'Vem är känd för TV-programmet Mat-Tina?', ARRAY['Tina Nordström', 'Lotta Lundgren', 'Sofia Henriksson', 'Jennie Walldén'], 0, 'easy', true),
  ('kp_030', 'famous_profiles', 'Vilken svensk profil kombinerar matlagning och inredning i TV?', ARRAY['Ernst Kirchsteiger', 'Tareq Taylor', 'Markus Aujalay', 'Niklas Ekstedt'], 0, 'medium', true),
  ('kp_031', 'famous_profiles', 'Vem är känd för restaurangen Spago i Los Angeles?', ARRAY['Wolfgang Puck', 'Gordon Ramsay', 'Nobu Matsuhisa', 'Thomas Keller'], 0, 'medium', true),
  ('kp_032', 'famous_profiles', 'Vem är känd för Netflix-serien Chef''s Table som berättare?', ARRAY['Anthony Bourdain', 'Ingen specifik kock', 'Massimo Bottura', 'David Gelb'], 3, 'hard', true),
  ('kp_033', 'famous_profiles', 'Vem är känd för att ha revolutionerat modern nordisk gastronomi?', ARRAY['René Redzepi', 'Gordon Ramsay', 'Alain Ducasse', 'Jamie Oliver'], 0, 'medium', true),
  ('kp_034', 'famous_profiles', 'Vem är svensk kock och programledare för Köket?', ARRAY['Catarina König', 'Jennie Walldén', 'Tina Nordström', 'Leif Mannerström'], 1, 'medium', true),
  ('kp_035', 'famous_profiles', 'Vem är känd för restaurangen Chez Panisse?', ARRAY['Alice Waters', 'Martha Stewart', 'Nigella Lawson', 'Julia Child'], 0, 'hard', true),
  ('kp_036', 'famous_profiles', 'Vem är känd för "nose-to-tail cooking"?', ARRAY['Fergus Henderson', 'Heston Blumenthal', 'Thomas Keller', 'Eric Ripert'], 0, 'hard', true),
  ('kp_037', 'famous_profiles', 'Vem är känd svensk krögare bakom flera krogar i Stockholm?', ARRAY['Melker Andersson', 'Ernst Kirchsteiger', 'Markus Aujalay', 'Tareq Taylor'], 0, 'medium', true),
  ('kp_038', 'famous_profiles', 'Vem är känd för TV-programmet Halv åtta hos mig som berättarröst?', ARRAY['Morgan Alling', 'Adam Alsing', 'Kristian Luuk', 'David Hellenius'], 0, 'easy', true),
  ('kp_039', 'famous_profiles', 'Vem är känd för att kombinera italiensk mat med TV-underhållning i Storbritannien?', ARRAY['Gennaro Contaldo', 'Massimo Bottura', 'Carlo Cracco', 'Marco Pierre White'], 0, 'hard', true),
  ('kp_040', 'famous_profiles', 'Vilken svensk profil är starkt förknippad med grillning och BBQ?', ARRAY['Jonas Cramby', 'Edward Blom', 'Per Morberg', 'Leif Mannerström'], 0, 'medium', true),
  ('kp_041', 'famous_profiles', 'Vem är känd för restaurangen Mirazur i Frankrike?', ARRAY['Mauro Colagreco', 'Alain Ducasse', 'Daniel Humm', 'Grant Achatz'], 0, 'hard', true),
  ('kp_042', 'famous_profiles', 'Vem är känd för programmet Landet Brunsås och sitt matintresse?', ARRAY['Lotta Lundgren', 'Tina Nordström', 'Jennie Walldén', 'Catarina König'], 0, 'easy', true),
  ('kp_043', 'famous_profiles', 'Vem är känd svensk stjärnkock och entreprenör med många restauranger?', ARRAY['Erik Lallerstedt', 'Niklas Ekstedt', 'Tommy Myllymäki', 'Markus Aujalay'], 0, 'medium', true),
  ('kp_044', 'famous_profiles', 'Vem är känd för TV-serien No Reservations?', ARRAY['Gordon Ramsay', 'Anthony Bourdain', 'Jamie Oliver', 'David Chang'], 1, 'easy', true),
  ('kp_045', 'famous_profiles', 'Vem är känd för koreansk matlagning i svensk TV?', ARRAY['Jennie Walldén', 'Tina Nordström', 'Lotta Lundgren', 'Catarina König'], 0, 'medium', true),
  ('kp_046', 'famous_profiles', 'Vem är känd för "Kitchen Nightmares"?', ARRAY['Gordon Ramsay', 'Jamie Oliver', 'Marco Pierre White', 'Wolfgang Puck'], 0, 'easy', true),
  ('kp_047', 'famous_profiles', 'Vilken svensk profil är både sommelier och TV-personlighet?', ARRAY['Mischa Billing', 'Edward Blom', 'Leif Mannerström', 'Markus Aujalay'], 0, 'medium', true),
  ('kp_048', 'famous_profiles', 'Vem är känd för restaurangen Central i Peru?', ARRAY['Virgilio Martínez', 'Gastón Acurio', 'Mauro Colagreco', 'René Redzepi'], 0, 'hard', true),
  ('kp_049', 'famous_profiles', 'Vem är känd för programmet Two Fat Ladies?', ARRAY['Clarissa Dickson Wright & Jennifer Paterson', 'Nigella Lawson & Jamie Oliver', 'Martha Stewart & Julia Child', 'Monica Galetti & Angela Hartnett'], 0, 'hard', true)

